package view;

import model.Question;
import storage.Storage;

public class PerguntaForm extends javax.swing.JFrame {

    private byte currentQuestion;
    private Question question;
    private int points;

    public PerguntaForm() {
        initComponents();
        txtQuestion.setWrapStyleWord(true);
        txtQuestion.setLineWrap(true);
        question = Storage.QUESTIONS[currentQuestion];
        setForm();
    }

    private void toNextQuestion() {
        currentQuestion++;
        if (Storage.QUESTIONS.length > currentQuestion) {
            question = Storage.QUESTIONS[currentQuestion];
            setForm();
        } else {
            System.out.println("GAME OVER");
        }
    }
    
    private void setForm() {
        txtQuestion.setText(question.getQuestion());
        resetRadios();
        rdAlt1.setText(question.getAlternatives()[0]);
        rdAlt2.setText(question.getAlternatives()[1]);
        rdAlt3.setText(question.getAlternatives()[2]);
        rdAlt4.setText(question.getAlternatives()[3]);
        lbCurrentQuestion.setText(String.valueOf(currentQuestion + 1));
        lbPoints.setText(String.valueOf(points));
    }
    
    private void resetRadios() {
        rdAlt1.setSelected(false);
        rdAlt2.setSelected(false);
        rdAlt3.setSelected(false);
        rdAlt4.setSelected(false);
    }

    // Events
    private void onSelectRadio(javax.swing.JRadioButton radio) {
        resetRadios();
        radio.setSelected(true);
    }
    
    private Question.Alternative getSelectedAlternative(){
        Question.Alternative alternative;
        if (rdAlt1.isSelected()) {
            alternative = Question.Alternative.A;
        } else if (rdAlt2.isSelected()) {
            alternative = Question.Alternative.B;
        } else if (rdAlt3.isSelected()) {
            alternative = Question.Alternative.C;
        } else {
            alternative = Question.Alternative.D;
        }
        return alternative;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCurrentQuestion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbPoints = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_dinheiro1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdAlt1 = new javax.swing.JRadioButton();
        rdAlt2 = new javax.swing.JRadioButton();
        rdAlt3 = new javax.swing.JRadioButton();
        rdAlt4 = new javax.swing.JRadioButton();
        btnReply = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pergunta:");

        lbCurrentQuestion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbCurrentQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lbCurrentQuestion.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("/50");

        lbPoints.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbPoints.setForeground(new java.awt.Color(255, 255, 255));
        lbPoints.setText("0");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("R$");

        lbl_dinheiro1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_dinheiro1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dinheiro1.setText(",00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCurrentQuestion)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(lbPoints)
                .addGap(0, 0, 0)
                .addComponent(lbl_dinheiro1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbCurrentQuestion)
                    .addComponent(jLabel3)
                    .addComponent(lbPoints)
                    .addComponent(jLabel5)
                    .addComponent(lbl_dinheiro1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(112, 128, 144));

        rdAlt1.setBackground(new java.awt.Color(112, 128, 144));
        rdAlt1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rdAlt1.setForeground(new java.awt.Color(255, 255, 255));
        rdAlt1.setText("Alternativa errada");
        rdAlt1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rdAlt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlt1ActionPerformed(evt);
            }
        });

        rdAlt2.setBackground(new java.awt.Color(112, 128, 144));
        rdAlt2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rdAlt2.setForeground(new java.awt.Color(255, 255, 255));
        rdAlt2.setText("Alternativa errada");
        rdAlt2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rdAlt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlt2ActionPerformed(evt);
            }
        });

        rdAlt3.setBackground(new java.awt.Color(112, 128, 144));
        rdAlt3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rdAlt3.setForeground(new java.awt.Color(255, 255, 255));
        rdAlt3.setText("Alternativa errada");
        rdAlt3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rdAlt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlt3ActionPerformed(evt);
            }
        });

        rdAlt4.setBackground(new java.awt.Color(112, 128, 144));
        rdAlt4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rdAlt4.setForeground(new java.awt.Color(255, 255, 255));
        rdAlt4.setText("Alternativa errada");
        rdAlt4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rdAlt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlt4ActionPerformed(evt);
            }
        });

        btnReply.setText("Responder");
        btnReply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplyActionPerformed(evt);
            }
        });

        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdAlt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnReply)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rdAlt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdAlt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdAlt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdAlt1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rdAlt2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rdAlt3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rdAlt4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnReply)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplyActionPerformed
        Question.Alternative alternative = getSelectedAlternative();
        if (question.reply(alternative))  {
            this.points += question.getPoints();
        }
        this.toNextQuestion();
    }//GEN-LAST:event_btnReplyActionPerformed

    private void rdAlt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlt1ActionPerformed
        onSelectRadio(rdAlt1);
    }//GEN-LAST:event_rdAlt1ActionPerformed

    private void rdAlt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlt2ActionPerformed
        onSelectRadio(rdAlt2);
    }//GEN-LAST:event_rdAlt2ActionPerformed

    private void rdAlt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlt3ActionPerformed
        onSelectRadio(rdAlt3);
    }//GEN-LAST:event_rdAlt3ActionPerformed

    private void rdAlt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlt4ActionPerformed
        onSelectRadio(rdAlt4);
    }//GEN-LAST:event_rdAlt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerguntaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerguntaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerguntaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerguntaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerguntaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCurrentQuestion;
    private javax.swing.JLabel lbPoints;
    private javax.swing.JLabel lbl_dinheiro1;
    private javax.swing.JRadioButton rdAlt1;
    private javax.swing.JRadioButton rdAlt2;
    private javax.swing.JRadioButton rdAlt3;
    private javax.swing.JRadioButton rdAlt4;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
